version: '3.8'

services:
  db:
    image: postgres:15
    container_name: schedule_db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: app_pass
      POSTGRES_DB: schedule_db
    volumes:
      - ../data/db:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

  backend:
    build: ./backend
    container_name: schedule_backend
    env_file: ./backend/.env
    depends_on:
      - db
    volumes:
      - ../data/files:/data/files
    ports:
      - "3001:3001"
    networks:
      - app_network
    restart: always

  frontend:
    build: ./frontend
    container_name: schedule_frontend
    env_file: ./frontend/.env.local
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
